### ISSUE TITLE
Formulaire Expertise, champs

### ISSUE THREAD

**Issue by Alex-Perrot** [theoplzr/AC_Process_Reporting_Project#2]
Première version des champs de formulaire d'expertise à fournir

**Comment by Alex-Perrot** [comment]
[https://acprocess0.sharepoint.com/sites/R_RetD/_layouts/15/guestaccess.aspx?share=EUARSTG9hRZDjg5Mr8_73YsB3oBEgU7AOqG80QzfEvFBgg&e=jMXjXZ](url)
document sur le drive, accès aussi via lien au dessus
@theoplzr @mark-355

**Comment by mark-355** [comment]
Réglé !
