### ISSUE TITLE
Formulaire Supervision

### ISSUE THREAD

**Issue by Alex-Perrot** [theoplzr/AC_Process_Reporting_Project#3]
Manque éléments du formulaire

**Comment by Alex-Perrot** [comment]
[https://acprocess0.sharepoint.com/sites/R_RetD/_layouts/15/guestaccess.aspx?share=EfWuQDq9xF5Pt0WD4McD5MwBTmiDGJ2n7_hr3F6HkrUpJg&e=RSxjGR](url)

cf. document via lien au dessus
@mark-355 @theoplzr posez vos questions ici si besoin, sinon cloture du ticket

**Comment by mark-355** [comment]
réglé
