### ISSUE TITLE
P1 - Possibilité de mettre une zone plutôt qu'un point ?

### ISSUE THREAD

**Issue by Alex-Perrot** [theoplzr/AC_Process_Reporting_Project#8]
Voir pour mettre la possibilité de créer une zone plutôt qu'un point, genre un carré un peu transparent, ou bien une forme libre même ? 

A redire

**Comment by theoplzr** [comment]
<img width="1103" alt="Capture d’écran 2024-10-21 à 11 27 00" src="https://github.com/user-attachments/assets/a816fb04-0f1f-43e5-ba46-86ea90367e40">

Si c'est bien comme ça que tu vois le truc, c'est OK du coup:)

**Comment by Alex-Perrot** [comment]
go très bien en V1
